name = "MyJuliaIntro"
uuid = "e57c0724-f49b-4ef3-9c1f-52274f33244b"
authors = ["David Métivier <david.metivier@inrae.fr>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
